CREATE DATABASE flaskr CHARACTER SET utf8;

DROP TABLE IF EXISTS customer;
CREATE TABLE customer (
  id VARCHAR(64) NOT NULL,
  name VARCHAR(16) null,
  phone VARCHAR(12) DEFAULT NULL,
  address VARCHAR(125) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
